# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20160115_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier', to='users.Cluster'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='minimum_order',
            field=models.IntegerField(default=0, verbose_name='minimum order'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='first_name',
            field=models.CharField(max_length=128, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='first_name',
            field=models.CharField(max_length=128, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='first_name',
            field=models.CharField(max_length=128, verbose_name='first name'),
        ),
    ]
