# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 18:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20160116_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='minimum_order',
        ),
    ]
