# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20160120_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='head',
            field=models.BooleanField(default=False, verbose_name='head of cluster'),
        ),
    ]
