# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date of visit')),
                ('next_visit', models.DateField(verbose_name='next visit')),
                ('doses_applied', models.IntegerField(verbose_name='doses applied')),
                ('mecicine_applied', models.CharField(default='Nilzan', max_length=20, verbose_name='medicine applied')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='users.Farmer')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='users.Worker')),
            ],
        ),
    ]
