# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='farmer',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='worker',
        ),
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
