# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_auto_20160115_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Cluster')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Supplier')),
            ],
        ),
        migrations.CreateModel(
            name='RequestItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Nilzan', max_length=20, verbose_name='name')),
                ('quantity', models.IntegerField(default='0', verbose_name='quantity')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.Request')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Worker')),
            ],
        ),
    ]
