# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20160115_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='target_date',
            field=models.DateField(default=orders.models.default_target_date),
        ),
    ]
