# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20160117_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='target_date',
            field=models.DateTimeField(default=orders.models.default_target_date, verbose_name='target date'),
        ),
    ]
