# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20160121_0656'),
        ('orders', '0005_auto_20160117_2107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='Nilzan Plus 1000 ml', max_length=20, verbose_name='description')),
                ('manufacturer', models.CharField(default='ICI', max_length=20, verbose_name='manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='ProductOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_order', models.IntegerField(default=0, verbose_name='minimum order')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='unit price')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_offers', to='orders.Product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_offers', to='users.Supplier')),
            ],
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'ordering': ['-submission_date']},
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='product',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='target_date',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='owner',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to='users.Worker'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlist',
            name='shipping_date',
            field=models.DateTimeField(default=orders.models.default_target_date, verbose_name='shipping date'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='status',
            field=models.CharField(choices=[('N', 'NEW'), ('P', 'PUBLISHED'), ('Q', 'QUOTED'), ('S', 'SHIPPED'), ('C', 'CANCELLED')], default='N', max_length=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to='users.Cluster'),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='quantity'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product_offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.ProductOffer'),
        ),
    ]
